config/routes.rb
Rails.application.routes.draw do
  root to: 'events#index'
  resources :events, only: [:show]
end

app/models/event.rb
class Event < ActiveRecord::Base
  def self.format_track(start, ending, track)
    event ||= Event.find_by(start: start, end: ending, track: track)
    all_track_event ||= Event.find_by(start: start, end: ending, track: ["Lunch", "Keynote", "Coffee Breaks", "Party"])
    if event
      event.name
    elsif all_track_event
      all_track_event.name
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @dates = Event.uniq.pluck(:start).map! { |t| t.strftime("%m/%d/%Y") }.uniq
  end

  def show
    month = params["id"][0..1]
    day = params["id"][3..4]
    real_date = day + "/" + month + "/" + params["id"][6..9]
    t = Date.parse(real_date)
    @events = Event.where(start: t..(t+1.day)).order("start ASC")
    @event = Event
    @tracks = Event.uniq.pluck(:track).sort.select { |t| t[0] == "T" }
    @times = @events.uniq.pluck(:start, :end)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/index.html.erb
<% @dates.each do |date| %>
  <%= link_to date, event_path(date) %><br>
<% end %>

app/views/events/show.html.erb
<table border="1" style="width:100%">
  <caption>Events</caption>
  <thead>
    <tr>
      <th></th>
      <% @tracks.each do |track| %>
        <th><%= track %></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @times.each do |time| %>
      <tr>
        <th><%= time[0].strftime("%m/%d/%Y %H:%M") %> to <%= time[1].strftime("%m/%d/%Y %H:%M") %></th>
        <% 5.times do |track_num| %>
          <td><%= @event.format_track(time[0], time[1], @tracks[track_num]) %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EventsCalendar</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>